services:
    flask_backend:
      container_name: flask
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      
      volumes:
        - .:/app
      restart: always
      
    mysql:
      container_name: mysql
      image: mysql:latest
      ports:
        - "3306:3306"
      volumes:
        - ./database:/docker-entrypoint-initdb.d/:ro
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: Hassan123+
        MYSQL_DATABASE: simulio   

    react_frontend:
      build: 
        context: ./web
        dockerfile: Dockerfile
      ports:
        - "5173:5173"
      volumes:
        - ./web/src:/app/src
      restart: always