services:
    flask_backend:
      container_name: flask
      build: 
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      
      volumes:
        - ./backend:/app
      restart: always
      
      depends_on:
      - mysql 
      
    mysql:
      container_name: mysql
      image: mysql:latest
      ports:
        - "3306:3306"
      volumes:
        - ./database:/docker-entrypoint-initdb.d/:ro
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: Hassan123+
        MYSQL_DATABASE: simulio   

    react_frontend:
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "5173:5173"
      volumes:
        - ./frontend/src:/app/src
      restart: always

    adminer:
      container_name: adminer
      image: adminer:latest
      ports:
        - "8080:8080"
      restart: always
      depends_on:
        - mysql